create or replace view V_CREATOR_PAYMENTS_UNION(
	PAYMENT_TYPE,
	REFERENCE_ID,
	REFERENCE_TYPE,
	STRIPE_CONNECTED_ACCOUNT_ID,
	STRIPE_CUSTOMER_ID,
	USER_ID,
	CREATOR_NAME,
	STRIPE_CONNECTED_ACCOUNT_NAME,
	STRIPE_CUSTOMER_NAME,
	COMPANY_NAME,
	CAMPAIGN_NAME,
	PAYMENT_STATUS,
	PAYMENT_AMOUNT,
	PAYMENT_DATE,
	CREATED_DATE
) as
Select * From V_CREATOR_PAYMENTS_DIRECTMODE
UNION
Select * From V_CREATOR_PAYMENTS_AGENCYMODE
UNION
Select * From V_CREATOR_PAYMENTS_UNASSIGNED;