-- File: examples/sql/initialsetup/01_create_ai_tables.sql
-- Create AI_VIEW_CONSTRAINTS table for security constraints
CREATE TABLE IF NOT EXISTS PF.BI.AI_VIEW_CONSTRAINTS (
    CONSTRAINT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    VIEW_NAME VARCHAR(255) NOT NULL UNIQUE,
    ALLOWED_OPERATIONS ARRAY,  -- ['SELECT', 'WHERE', 'GROUP BY', etc.]
    FORBIDDEN_KEYWORDS ARRAY,  -- ['DROP', 'DELETE', 'UPDATE', etc.]
    MAX_ROWS NUMBER DEFAULT 10000,
    COLUMN_WHITELIST ARRAY,  -- Allowed columns for querying
    COLUMN_DESCRIPTIONS VARIANT,  -- JSON with column names and descriptions
    EXAMPLE_VALUES VARIANT,  -- Sample data to help Cortex understand
    BUSINESS_RULES TEXT,  -- Domain-specific rules for this view
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create AI_CORTEX_PROMPTS table for optimized prompts
CREATE TABLE IF NOT EXISTS PF.BI.AI_CORTEX_PROMPTS (
    PROMPT_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PROMPT_NAME VARCHAR(255) NOT NULL,
    VIEW_NAME VARCHAR(255),
    PROMPT_TEMPLATE TEXT NOT NULL,
    EFFECTIVENESS_SCORE NUMBER(3,2),  -- Track which prompts work best
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
